Project60/org.project60.banking

- extension/banking.php
Fix #167
Changes argument in CRM_Utils_File::sourceSQLFile call to file instead of sql string
(I checked it with 4.7.20, not with older versions)
> Fix #167, compatibility with CiviCRM 4.7.20

- extension/CRM/Banking/PluginImpl/Importer/CSV.php
- extension/CRM/Banking/PluginImpl/Importer/Fixed.php
This adds support for all encodings supported by iconv. Previously, encodings not supported by PHP's multibyte string library would cause errors.
This also fixes an issue with files containing multibyte strings when processed using the fixed width import plugin.
> Add iconv and multibyte support

- extension/hooks.php
When banking was in the main menu a separator line was shown above the main menu
The line is only added when banking is in the Contributions Menu
> Fixed separtor in main navigation menu

- extension/CRM/Banking/PluginImpl/PostProcessor/MembershipExtension.php
When you want to extend a membership with a newly created contribution from CiviBanking. You can use the post processor to link this payment to the membership and extend it. 
However if there are already payments linked to the membership the membership gets extended but the payment does **not** get linked to the membership. 
This PR fixes that.
> Linking a new payment for a membership in membership extension post processor

- extension/CRM/Banking/Page/Review.php
When the new ui is enabled and you reviewed the last transaction in the list you got redirected to the old ui.
Redirect to new ui statement list after reviewing the last last transaction.
> fixed redirect after reviewing last statement in new ui

- extension/CRM/Admin/Form/Setting/BankingSettings.php
Since CiviCRM 5.12.0 updating the settings caused a fatal error. This was caused because the function CRM_Core_BAO_Navigation::buildNavigation has been removed.
> Fixed issue with banking and civicrm > 5.12.0

- extension/CRM/Banking/PluginImpl/Matcher/RulesAnalyser.php
This fixes a minor `E_NOTICE` when accessing `lookup_contact_by_name` when it's not set in the plugin configuration.
> Fix notice for undefined property in RulesAnalyser

- extension/CRM/Banking/PluginImpl/PostProcessor/MembershipPayment.php
This fixes an issue where the empty index operator is applied to a string, which causes a fatal error with PHP 7.1.
Reference: https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-index-operator
> Fix fatal error in MembershipPayment processor with PHP 7.1

- extension/CRM/Banking/PluginImpl/Importer/CSV.php
We were facing problems with some bank statement imports that included amounts with the German formatting including thousand separators like `10.000,00` which resulted in an imported amount of "10.00" instead of "10000.00".
As I failed to write a RegexAnalyser to fix the values I patched the Importer and propose this PR.
> improve CsvImporter 'amount' to filter thousand separators

- extension/CRM/Banking/PluginModel/Importer.php
Sometimes the generated statement reference exceeds the varchar(64) limit in the database and throws an unknown DB error. Please consider updating the DB schema, or limit the generation of the reference to the appropriate length. This issue was caused only by a specific importer plugin and only sometimes - ie. when "-DUPLICATE-$counter" was added to the reference string, or when {starting_date} was longer.
> Limit imported statement reference lenght to avoid exceeding it

- extension/CRM/Admin/Form/Setting/BankingSettings.php
- extension/CRM/Banking/BAO/BankAccount.php
- extension/CRM/Banking/Matcher/Context.php
- extension/CRM/Banking/Page/Review.php
- extension/CRM/Banking/Upgrader.php
- extension/banking.php
- extension/templates/CRM/Admin/Form/Setting/BankingSettings.tpl
- extension/templates/CRM/Banking/Page/ReviewDebtor.tpl
**Current situation**
When a transaction is matched by bank account this contact gets a probability of 100%. Meaning that in some matchers the transaction is matched with 100% certainity to this contact. 
Sometimes this is not the desired situation. 
For example in an organization where membership are stored on the household the individual might pay for the membership and as soon as the bank account is stored at the person level all other 'magic' disappears for identifying the household and the payment is recorded at the individual with 100% certainty and therefor the matcher is executed automatically.
**Proposed solution**
A setting where we can set the percentage for probability for bank account matching. In the above use case I am then able to lower the certainty so that automatic …
> implemented probability setting for bank account matching

- extension/CRM/Banking/PluginImpl/Matcher/RulesAnalyser.php
This fixes an issue where Smarty calls count() on an object that is implicitly cast to array and does not implement Countable.
See https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types
We implemented this last year via 4e18005600a35a2a252d89f69d1d6602a30d3a4c and a7e767a9af570ceb0da8b313effbc31964cea1eb, but forgot to upstream. 😢
> GP-6866 Fix PHP 7.2 warning when using count() on object

- extension/CRM/Banking/RuleMatchIndicators.php
This fixes an issue where empty names in banking transaction causes the name-based rule match lookup to throw an exception.
> GP-5333 Fix empty name cause exception in rule match lookup

- extension/CRM/Banking/Form/StatementSearch.php
- extension/css/banking.css
- extension/templates/CRM/Banking/Page/ReviewDetails.tpl
- extension/templates/CRM/Banking/Page/ReviewPurpose.tpl
In some parts of the UI where values may be used for searches or as part of banking rules, whitespace sequences (i.e. two spaces) may be significant and would cause a rule/search not to match when these values are copied and pasted without the sequence.
HTML's default behaviour is to ignore whitespace sequences. This changes the whitespace handling to show things like two consecutive spaces so that values may be copied safely.
The change is applied to the purpose/detail view on the transaction review page, and the purpose column of statement search.
> Show whitespace sequences in UI if they're significant

- extension/CRM/Banking/BAO/PluginInstance.php
fix #346
Thanks to @sebalis and @Detsieber for working this out with me! 💪
It looks like the entire call to `OptionGroup.get` for receiving the option group id is unnecessary, so we removed that.
https://github.com/Project60/org.project60.banking/blob/ea20fd3a5cd5df44f7acf0754039ee97c5aef569/extension/CRM/Banking/BAO/PluginInstance.php#L50-L52
We changed the `OptionValue.get` call to an `OptionValue.getsingle` call to make sure it can only return one value. Also we renamed the `group_id` parameter to `option_group_id` and passed the hardcoded string for the plugin classes.
```php
// find the correct plugin type
$import_plugin_type = civicrm_api3('OptionValue', 'getsingle', array(
'name'     => $type_name,
'option_group_id' => 'civicrm_banking.plugin_classes'));
```
> fix #346 | wrong parameter name for option group id

- extension/templates/CRM/Banking/Page/Statements.tpl
Fixes the fact that the form does not submit correctly otherwise.
Tested and working on CiviCRM 5.37.0.
> Change statements filter method from GET to POST

- extension/CRM/Banking/PluginImpl/Importer/CSV.php
See https://github.com/Project60/org.project60.banking/issues/300
I have not added the BOM-Skipping in the sentinel test, perhaps someone wants to test for the BOM.
> Skip BOM in CSV importer, e.g. for Paypal

- extension/CRM/Banking/Page/AccountDedupe.php
This fixes a bug in the dedupe screen to exclude the bank accounts which are not linked to a contact. 
See #367
> Fix for issue #367

- extension/Civi/Banking/Actions/FindLatestAccount.php
- extension/Civi/Banking/CompilerPass.php
> Add action find latest account for contact

- composer.json
@bjendres This PR adds a `composer.json` file inside the repository.
On the remote project, one needs to do the following to include CiviBanking:
Extract from `composer.json` :`
```json
{
"name": "xxx",
"description": "xxx",
"type": "civicrm-ext",
"license": "xxxx",
"require": {
"civicrm/banking": "1.0.0" <-- tag goes here
},
"repositories": [
{
"type": "vcs",
"url": "https://github.com/ixiam/org.project60.banking.git"
}
]
}
```
This PR has been tested on my local `composer` builder and it did work as expected.
You've probably noticed that the 2 libraries that you use (eval-math & the json viewer) where not being included in the `composer.json` file.   
This is because it got way too much complicated by trying to add them so since you are not having so frequent updates on those libraries, …
> Adds composer.json to the repository

- banking.php
**It throws error**
`Error: Class 'E' not found in banking_civicrm_tabset()`
> Fix translation class not found error

- CRM/Banking/Helpers/OptionValue.php
- CRM/Banking/Matcher/Engine.php
- CRM/Banking/Page/AccountDedupe.php
- CRM/Banking/PluginImpl/PostProcessor/MembershipExtension.php
- CRM/Banking/PluginModel/Base.php
- CRM/Banking/Rules/Rule.php
- CRM/Banking/Upgrader/Base.php
- api/v3/BankingLookup.php
- api/v3/BankingRule/Updatesearchresults.php
- api/v3/BankingTransaction.php
- configuration_database/Legacy_Configurations/importer/fixed/CH-LSV-v11.json
Various smaller fixes and adjustments that should grant CiviBanking compatibility with CiviCRM5.60+ and PHP8
> CiviCRM5.60+ and PHP8 compatibility

- api/v3/BankingPluginInstance/Import.php
This exposes the existing file import functionality as an API3. We use this as part of our automation to import CAMT files.
(Our import process is implemented as an SQL Task. It's available [here](https://github.com/user-attachments/files/16747486/CiviBanking.Import.share.sqltask.json) if anyone wants to use it as a starting point, though please note that some of it is highly specific to our environment.)
> GP-8788 Add BankingPluginInstance import API

- banking.php
I couldn't find any specific contribution guidelines for this project, so I did my best to address this issue. If I missed any steps or requirements, just let me know :)
This PR addresses issue Project60/org.project60.banking#434 with the NavMenu icon in the CiviBanking extension after upgrading to CiviCRM Core ^5.77. The recent upgrade introduced a major change in Font Awesome, shifting from version 4 to version 6, which deprecated several older class names, including fa fa-btc.
Utilized the crm-i wrapper for Font Awesome, as recommended in the [CiviCRM developer documentation](https://lab.civicrm.org/documentation/docs/dev/-/blob/master/docs/framework/ui.md?ref_type=heads#icons) to maintain compatibility with future updates.
Manually verified that the NavMenu icon is displayed correctly …
> Fix NavMenu Icon for Compatibility with CiviCRM Core 5.77/Font Awesome 6

- CRM/Admin/Form/Setting/BankingSettings.php
Hi,
due a mixup of variables, an incorrect value (`$new_menu_position`) is currently stored for the JSON editor mode if user edit the banking settings. This leads to an exception with a message about an invalid mode, the JSON editor fails to load. Could you merge this fix and release a new version? Thanks!
> fix storing of json_editor_mode

- CRM/Banking/Form/AccountsTab.php
Passing `true` as `$attributes` in `add()` triggers a deprecated error and has no impact.
> AccountsTab: Avoid deprecated method call

- CRM/Banking/Matcher/Context.php
Keep probability of already found contacts and do not overwrite them … with the bank account reference matching probability
See #397
> Fix for #397

- CRM/Banking/PluginImpl/Importer/CSV.php
- docs/configuration/plugins/importers/csv.md
Added new config option `line_filter_use_delimiter` to activate behavior described in #443.
Existing configs use the old separator ',' - so existing workflows remain unchanged.
One can switch to the new behavior by adding `line_filter_use_delimiter` to the config.
I also added a progress message to show the number of filtered out lines and a short description in `docs/configuration/plugins/importers/csv.md`.
Accidentally PR against branch master - should it be 1.2.x?
> Use configured separator for matching line_filter

- api/v3/BankingLookup.php
Relates to #403, #439, #424
systopia-reference: 27907
> Use APIv4 for contact lookup and improve probability calculation

- CRM/Banking/Matcher/Context.php
In #460 we encountered a problem which was caused by the following:
In version 1.3 the `BankingLookup.contactbyname` api is refactored to use the core API4 `Contact.autocomplate` instead of the old v3 `contact.getquick`. At our environment (civicrm version 5.76) we did not have that old api. So the `BankingLookup.contactbyname` returned an error and no suggestions at all. The fix in banking 1.3 fixed this and thus returned a list of contacts.
This list contacts was found by the name and the probability was 99%. Which is good. However if a contact is also found as an account own the probability is not upgraded to 100%.
This PR fixes that,
> Fixed #460 when contacts are found by their name and as account owner
