Project60/org.project60.banking

extension/CRM/Banking/PluginImpl/Matcher/RegexAnalyser.php
extension/CRM/Banking/PluginModel/Matcher.php
extension/api/v3/BankingLookup.php

Replace deprecated (php5) / removed (php7) function split() with preg_split()

Make it compatible with php7

---

extension/CRM/Banking/PluginModel/Matcher.php

I need braces, curly ones
Fixes error:
Notice: Array to string conversion

Fix php array to string conversion

---

extension/CRM/Banking/PluginImpl/Matcher/Membership.php

fixed membership suggestion execution for multiple memberships

---

extension/CRM/Banking/PluginModel/BtxBase.php

exptected to expected

---

extension/CRM/Banking/Page/Manager.php
extension/CRM/Banking/Page/Review.php
extension/CRM/Banking/Page/StatementLine.php
extension/CRM/Banking/Page/Statements.php
extension/CRM/Banking/Upgrader.php
extension/banking.php
extension/banking_options.php
extension/hooks.php
extension/templates/CRM/Banking/Page/Manager.tpl
extension/templates/CRM/Banking/Page/Review.tpl
extension/templates/CRM/Banking/Page/StatementLine.tpl
extension/templates/CRM/Banking/Page/Statements.tpl
extension/xml/Menu/banking.xml

See issue #200 for description.

Fixed #200 new UI for civibanking

---

extension/hooks.php

Small fix for #88 until #95 implemented

Set proper permission to Banking main menu

---

extension/CRM/Banking/BAO/PluginInstance.php

As a newbie, you spend a lot of time searching and looking in the examples. Having them easier to read would make it easier.

pretty print the export json

---

extension/api/v3/BankingLookup.php

This seems to work way faster without any downside
@systopia I'm not sure I got the logic of avoiding 1.0 as probability, should it apply if exact match too?

fix #214, add a fast mode if sort_name matches exactly

---

mkdocs.yml

New YAML format for mkdocs file.

[#230] mkdocs.yml format

---

extension/CRM/Banking/Page/Statements.php
extension/templates/CRM/Banking/Page/Statements.tpl

**Before**
In the new UI the export button was missing.
**After**
The export button added to the new UI
**See also**
https://github.com/Project60/org.project60.banking/issues/276

Issue #276: export button in new UI

---

README.md

Docu links updated, as suggested by bendres.

Update README.md to official documentation

---

extension/templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl

[#301] fix NaN in default options matcher summary field

---

extension/Civi/Banking/Actions/AddIban.php
extension/Civi/Banking/CompilerPass.php
extension/banking.php
extension/info.xml

This PR add the action (Form Processor/Action Provider) to add an IBAN to a contact. Required for AIVL, tested locally.

fixes #355 - add action to add iban to contact

---

extension/CRM/Banking/PluginImpl/Importer/CSV.php

Adjusted PR based on the work of @being-peace in #330

Skip BOM in CSV importer

---

extension/CRM/Banking/PluginImpl/Importer/CSV.php

This has been around for a while, see #300, #330, #373.
Thanks, @being-peace.
Note: still needs to be merged into ``master``

Strip BOM in CSV importer

---

CRM/Banking/Page/Import.php
CRM/Banking/PluginImpl/Importer/XML.php
CRM/Banking/PluginModel/Importer.php

This is an addition to the file importer: when it encounters a ZIP file in the upload, the importer will extract all files on the top level, and runs the selected importer configuration on all of them.

Multi-File Import via ZIP files

---

docs/configuration/plugins/analyser-matcher.md
docs/configuration/plugins/concept.md
docs/configuration/plugins/importer-actions.md
docs/index.md
docs/reference.md
info.xml
mkdocs.yml

Fix #401 
Updated the documentation sections for import, analysers and matchers, provided more information for implementers based on  compact examples.

Documentation updates

---

css/banking.css
templates/CRM/Banking/PluginImpl/Matcher/DefaultOptions.suggestion.tpl

The function to remove a manually added contribution was not working.
Also: CSS adapted to change cursor to pointer on anchor tag.

fix: remove element from contribution list

---

CRM/Banking/PluginImpl/Importer/CSV.php

PR against 1.2.x - or should it be master?

Add CSV parse options enclosure and escape - #445

---

Civi/Banking/CompilerPass.php
Civi/Banking/DataProcessor/FieldoutputHandler/ContactIBANOutputhandler.php
Civi/Banking/DataProcessor/Source/BankAccount.php

This PR contains an integration with the data processor. The integration is the following:
* A field output handler for displaying the most recent IBAN of an contact
* A data source for the Bank Account (which also links to the bank account reference)

Added data processor for bank account

---

CRM/Banking/PluginImpl/Exporter/CSV.php

I needed an export feature to append two fields. So here is my PR for this.
It has been tested already and is working as expected.
I used the code of the append-feature of the CSV-Importer as a reference.

Add an append feature to the CSV Exporter

---

templates/CRM/Banking/Page/AccountSearch.tpl
templates/CRM/Banking/Page/Export.tpl
templates/CRM/Banking/Page/Import.tpl
templates/CRM/Banking/Page/Statements.tpl

Improves accessibility for assistive technology.
See https://github.com/civicrm/civicrm-core/pull/33588

dev/core#5041 - Add role + aria-hidden to FontAwesome icons
